### ISSUE TITLE
Failed to create key-pair

### ISSUE THREAD

**Issue by SelimGribaa** [lyokato/WebAuthnKit-iOS#10]
Hello, 

I created a new project to test your library, with the same configuration and the same classes that you used in your Demo (WebAuthnKitDemo). I used the exact same code and I have this error:

[WebAuthnKit]<ECDSAKeySupport> failed to create key-pair: inconcistency(message: "Couldn\'t create access control flag. Keychain chokes if you try to create access control with only [.privateKeyUsage] on devices older than iOS 11 and macOS 10.13.x")

And when I test directly on your project everything works fine, and I use the same device. it's absurd. I hope to have an answer because I have been stuck for a week. thank you in advance

**Comment by lyokato** [comment]
This caused by version difference of EllipticCurveKeyPair library.

I bumped version of dependencies, and removes bugs.

https://github.com/lyokato/WebAuthnKit-iOS/pull/11
